### ISSUE TITLE
To-Do List

### ISSUE THREAD

**Issue by efectn** [efectn/library-management#7]
**Stage 1:**
- [ ] Add more tests for utils, database etc.
- [ ] Add more seeders.
- [ ] Make structure more clean.
- [ ] Complete base.
